spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/app
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8006