spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8006