services:
  postgres:
    image: postgres:latest
    container_name: post
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
